LIHARFBUZZ_OPENIPC_VERSION = 8.3.1
LIHARFBUZZ_OPENIPC_SITE = https://github.com/harfbuzz/harfbuzz/releases/download/$(LIHARFBUZZ_OPENIPC_VERSION)
LIHARFBUZZ_OPENIPC_SOURCE = harfbuzz-$(LIHARFBUZZ_OPENIPC_VERSION).tar.xz

LIHARFBUZZ_OPENIPC_LICENSE = OLD MIT
LIHARFBUZZ_OPENIPC_LICENSE_FILES = LICENSE
LIHARFBUZZ_OPENIPC_DEPENDENCIES += host-meson

define LIHARFBUZZ_OPENIPC_CONFIGURE_CMDS
	meson setup $(LIHARFBUZZ_OPENIPC_CONF_OPTS) $(@D) $(@D)/build
endef

define LIHARFBUZZ_OPENIPC_BUILD_CMDS
	ninja -C $(@D)/build
endef

$(eval $(generic-package))
